<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lawcription Terms & Conditions</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100 text-gray-800">

    <!-- Header -->
    <header class="bg-blue-900 text-white py-6 shadow-md">
        <div class="max-w-5xl mx-auto px-4 flex items-center justify-between">

            <!-- Left Side -->
            <div>
                <h1 class="text-2xl font-bold">Lawcription</h1>
                <p class="text-sm opacity-90">Operated by Healthcription</p>
            </div>

            <!-- Right Side Links -->
            <nav class="space-x-6 text-sm font-medium">
                <a href="{{route('user.privacy')}}" class="hover:underline hover:text-gray-200 transition">
                    Privacy Policy
                </a>
                <a href="{{route('user.about')}}" class="hover:underline hover:text-gray-200 transition">
                    About Us
                </a>
            </nav>

        </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-5xl mx-auto bg-white shadow-lg rounded-lg p-8 my-8 leading-relaxed">

        <h2 class="text-xl font-bold mb-4 text-center">TERMS AND CONDITIONS OF USE</h2>

        <h3 class="font-semibold mt-6 mb-2">1. PREAMBLE, OWNERSHIP & STATUTORY COMPLIANCE</h3>
        <p>This document is an electronic record in terms of the <b>Information Technology Act, 2000</b> and rules thereunder. This agreement is generated by a computer system and does not require physical or digital signatures.</p>

        <p><b>Lawcription</b> is a digital platform and brand operated under <b>Healthcription</b>, a sole proprietorship owned by <b>Mrs. Poulomi Debnath</b>. These Terms and Conditions (“Terms”) constitute a legally binding and enforceable contract between the User and <b>Healthcription</b> (operating as <b>Lawcription</b>) (“Owner”, “We”, “Us”, “Our”). All services, payments, and legal obligations are undertaken by <b>Healthcription</b>.</p>

        <p>Accessing or using the <b>Lawcription</b> mobile application (“App”), operated by <b>Healthcription</b>, implies an unconditional acceptance of these Terms, drafted in strict consonance with:</p>

        <ul class="list-disc ml-6">
            <li><b>The Bharatiya Nyaya Sanhita, 2023</b> (and the erstwhile Indian Penal Code, 1860).</li>
            <li><b>The Indian Contract Act, 1872</b>.</li>
            <li><b>The Digital Personal Data Protection Act, 2023</b>.</li>
            <li><b>The Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021</b>.</li>
            <li><b>The National Medical Commission (Professional Conduct, Etiquette and Ethics) Regulations, 2023</b>.</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">2. DEFINITIVE INTERPRETATION</h3>
        <ul class="list-disc ml-6">
            <li><b>"App"</b>: Refers to the <b>Lawcription</b> mobile application (operated by <b>Healthcription</b>), its user interface, source code, and integrated services.</li>
            <li><b>"Content"</b>: Includes, but is not limited to, medico-legal templates, statutory summaries, case law analyses, and educational modules.</li>
            <li><b>"User"</b>: Any natural or legal person who downloads, installs, or browses the App.</li>
            <li><b>"Healthcare Professional"</b>: A practitioner registered with the National Medical Commission (NMC) or State Medical Councils.</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">3. DECLARATION OF COMPETENCY</h3>
        <p>By accessing the App, the User represents and warrants that:</p>
        <ul class="list-disc ml-6">
            <li>They possess the legal capacity to enter into a binding contract under <b>Section 11 of the Indian Contract Act, 1872</b>.</li>
            <li>All information provided during registration is veracious, current, and complete.</li>
            <li>Any misrepresentation shall be subject to prosecution under <b>Sections 318 & 319 of the Bharatiya Nyaya Sanhita, 2023</b> (Cheating and Impersonation).</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">4. SCOPE OF SERVICES & LEGAL DISCLAIMER</h3>
        <p><b>Lawcription</b>, operated by <b>Healthcription</b>, operates strictly as an Educational Resource and Compliance Support Tool.</p>
        <ul class="list-disc ml-6">
            <li><b>No Attorney-Client Privilege</b>: Use of this App does not establish a lawyer-client relationship.</li>
            <li><b>Informational Nature</b>: The content provided is for informational purposes and does not constitute legal advice.</li>
            <li><b>Professional Responsibility</b>: Medico-legal templates are "standardized drafts." Users are mandated to exercise professional discretion and consult independent legal counsel for specific litigation or advisory matters.</li>
            <li><b>No Medical Practice</b>: <b>Lawcription</b>, operated by <b>Healthcription</b>, does not engage in the practice of medicine or provide clinical diagnostic services.</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">5. INTELLECTUAL PROPERTY & PROPRIETARY RIGHTS</h3>
        <p>The App and its entire contents (text, graphics, logos, and software) are the exclusive Intellectual Property of <b>Lawcription</b>, operated by <b>Healthcription</b>, protected under the <b>Copyright Act, 1957</b> and <b>Trademarks Act, 1999</b>.</p>
        <ul class="list-disc ml-6">
            <li><b>License Grant</b>: Users are granted a revocable, non-exclusive, non-transferable license for personal/professional reference only.</li>
            <li><b>Restrictive Covenant</b>: Any attempt to reverse-engineer, scrape, redistribute, or commercially exploit the Content without prior written consent shall result in immediate termination and suit for damages.</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">6. FINANCIAL OBLIGATIONS & REFUND POLICY</h3>
        <ul class="list-disc ml-6">
            <li><b>Consideration</b>: Subscription fees are inclusive of all applicable taxes.</li>
            <li><b>Finality of Sale</b>: Given the digital and "consumable" nature of the content, all payments are final and non-refundable.</li>
            <li><b>Statutory Exceptions</b>: Refunds shall only be processed in cases of documented technical failure where the service was not rendered, within 7–14 business days through the original payment source.</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">7. DATA PRIVACY & THE DPDP ACT, 2023</h3>
        <p><b>Healthcription</b> (operating as <b>Lawcription</b>) acts as a Data Fiduciary. By using the App, the User consents to the processing of personal data as per our Privacy Policy.</p>
        <ul class="list-disc ml-6">
            <li><b>User Rights</b>: In accordance with the <b>DPDP Act, 2023</b>, Users may exercise their right to summary, correction, and erasure of personal data.</li>
            <li><b>Confidentiality</b>: <b>Lawcription</b>, operated by <b>Healthcription</b>, employs industry-standard encryption. However, the User is cautioned against uploading sensitive patient-identifiable information (PII) that violates patient confidentiality norms.</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">8. INDEMNITY AND LIMITATION OF LIABILITY</h3>
        <ul class="list-disc ml-6">
            <li><b>Indemnification</b>: The User agrees to indemnify, defend, and hold harmless <b>Healthcription</b> (operating as <b>Lawcription</b>) from any claims, losses, or legal expenses arising out of the User’s breach of these Terms or misuse of medico-legal templates.</li>
            <li><b>Limitation of Liability</b>: In no event shall the aggregate liability of <b>Healthcription</b> exceed the total subscription fee paid by the User in the twelve (12) months preceding the claim.</li>
            <li><b>Excluded Damages</b>: We are not liable for any indirect, incidental, or consequential damages (including loss of professional reputation).</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">9. DISPUTE RESOLUTION & JURISDICTION</h3>
        <ul class="list-disc ml-6">
            <li><b>Governing Law</b>: This agreement is governed by the substantive and procedural laws of the Republic of India.</li>
            <li><b>Arbitration</b>: Any dispute arising out of this agreement shall be referred to a Sole Arbitrator in accordance with the <b>Arbitration and Conciliation Act, 1996</b>.</li>
            <li><b>Seat and Jurisdiction</b>: The seat of arbitration and exclusive jurisdiction for all matters shall be Kolkata, West Bengal.</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">10. GRIEVANCE REDRESSAL</h3>
        <p>In compliance with the <b>Information Technology Rules, 2021</b>, all grievances or legal notices must be addressed to the Grievance Officer at:</p>
        <ul class="list-disc ml-6">
            <li><b>Email</b>: lawcriptionadmin@gmail.com</li>
        </ul>

        <h3 class="font-semibold mt-6 mb-2">ADVISORY NOTE</h3>
        <p>Continued use of the App, <b>Lawcription</b>, operated by <b>Healthcription</b>, following any amendments to these Terms constitutes "Deemed Acceptance". Users are advised to review this section periodically.</p>

    </main>

    <!-- Footer -->
    <footer class="bg-gray-900 text-white text-center py-4">
        <p class="text-sm">&copy; 2026 Healthcription (Lawcription). All Rights Reserved.</p>
    </footer>

</body>

</html>